### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by HarryR** [HarryR/ethsnarks#46]
What would another 6-8 months of successful development on ethsnarks look like? What is success?

Ultimately this is making a set of thoroughly-tested components available to developers in a way which makes using zkSNARKS viable for their Ethereum compatible project.

As a developer it should be easy to get started, with documented examples of everything they need to use ethsnarks with their project. Ideally the combination of ethsnarks and related documentation will significantly reduce the time-to-market for projects using zkSNARKs on Ethereum, and have unique advantages that other projects don't which make it a safe choice.

## High-level

 * [ ] [Pinocchio](https://eprint.iacr.org/2013/279) and [xjsnark](https://github.com/akosba/xjsnark) compiler support
 * [ ] End-to-end tests for Miximus
 * [ ] Example of deploying verifier on-chain
 * [ ] [Baby JubJub](https://github.com/barryWhiteHat/baby_jubjub_ecc) in-SNARK elliptic curve support
 * [ ] Use case documentation

## Specifics 

 * [ ] [Pinocchio](https://eprint.iacr.org/2013/279) and [xjsnark](https://github.com/akosba/xjsnark) compiler support
   * [ ] Generate proving key, verification key, proof (as .json) via cli
   * [ ] .so/.dll/.dylib support, for embedding into a program
   * [ ] Import pinocchio compiler (into a sub-repo), provide examples
   * [ ] Verify opcode functionality, compatibility
   * [ ] Support both native field elements and bit types in Pinocchio
 * [ ] End-to-end tests for Miximus
   * [ ] NodeJS wrapper for the prover .dll/.so file
   * [ ] Deposit, Withdraw, using the prover
 * [ ] Baby JubJub support
   * [ ] More extensive edge-case tests
   * [ ] Circuit optimisations
   * [ ] Python implementation + tests
   * [ ] Solidity implementation + tests + gas costs
 * [ ] Use case documentation
   * [ ] Building a circuit in C++ - getting JSON output + CLI for free, via cli stubs
   * [ ] Integrating a zkSNARK verifier into your solidity project
   * [ ] Compiling C using Pinocchio
   * [ ] Integrating with xjsnark
   * [ ] Using baby jubjub
